name: Deploy
 
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04
        timeout-minutes: 30
        steps:
            -   run: ls -la
            -   uses: actions/checkout@master
            -   run: sudo apt update && sudo apt upgrade

            -   run: sudo apt-get install rsync

            - name: Deploy to Remote Server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 80
                # dest: 'dikamen@"${{ secrets.SERVER_HOST }}":/usr/share/nginx/html'
                script: |
                  docker-compose -f ././docker-compose.yml pull
                  docker-compose -f ././docker-compose.yml up -d

            # -   name: Display status from deploy
            #     run: echo "${{ steps.deploy.outputs.status }}"
