name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Build and Deploy
      run: |
        # Ваш скрипт для сборки и выгрузки файлов
        # Например, использование npm, make, или других инструментов

    - name: SCP files to Ubuntu Server
      uses: appleboy/scp-action@v0.3.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "quiz/"
        target: "/quiz-deployment/quiz-html"

    - name: SSH into Ubuntu Server
      uses: appleboy/ssh-action@v0.6.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /path/on/remote/server
          docker-compose down
          docker-compose up -d
